apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache
  namespace: app-web
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  serviceName: apache
  replicas: 2
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: apache
          mountPath: /var/www/html
  volumeClaimTemplates: # necessario definir o volumeClaim, pois setamos um volume no container
  - metadata:
      name: apache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi        
 