apiVersion: v1
kind: Service
metadata:
  name: apache-nodeport
  namespace: app-web
  labels:
    app: apache
spec:
  selector:
    app: apache
  ports:
  - port: 80
    nodePort: 32700
  type: NodePort
