apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None # Sem IP, é nesse ponto que define o service headless
  selector:
    app: nginx
