apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-antiaffinity-region
  name: nginx-antiaffinity-region
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-antiaffinity-region
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-antiaffinity-region
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity: # regra para informar qual será os Pods que entrarao na regra de anti afinidade.
          requiredDuringSchedulingIgnoredDuringExecution: # Significa que é requirido (required) q a regra seja aplicada no momento de Schedule do Pod ignorando a execução
          - labelSelector: # define qual vai ser a label do Pod que irá ser aplicado a regra
              matchLabels:
                app: nginx-antiaffinity-region # tudo que fizer match com a "app: nginx-affinity-region" ira ser aplicado a regra de anti afinidade
            topologyKey: "region" # nao permitira provisionar mais de um Pod com label "app: nginx-affinity-region" no mesmo nodo que possui a label "region"
                  
