apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-preferredscheduling
  name: nginx-preferredscheduling
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-preferredscheduling
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-preferredscheduling
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity: # regra para informar qual será os Pods que entrarao na regra de anti afinidade.
          preferredDuringSchedulingIgnoredDuringExecution: # Significa que de preferencia (preferred) a regra seja aplicada no momento de Schedule do Pod ignorando a execução
          - weight: 1 # aplicando um peso para a regra. Se tiver duas regras "preferred" será aplicada a regra que tiver o peso mais alto
            podAffinityTerm: # usado somente para o "preferred" para "required" é "nodeSelectorTerms"
              labelSelector:
                matchLabels:
                  app: nginx-preferredScheduling
              topologyKey: "az" # De preferencia será escalado 1 Pod "nginx-preferredScheduling" no host que possui o label "az"
                  
