apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-secret
    image: nginx
    env: # definindo secret como variável de ambiente dentro do POD
    - name: USERNAME
      valueFrom:
        secretKeyRef: # a referência da chave secret
          name: secret-opaque # usa o secret já criado
          key: username # atribui ao username do secret criado, o valor
    - name: PASSWORD
      valueFrom:
        secretKeyRef: # a referência da chave secret
          name: secret-opaque
          key: password
    resources:      
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"
              


