apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
  - name: giropops-autenticado
    image: bebianc/linuxtips-giropops-senhas:7.0
  imagePullSecrets: # passamos aqui qual Secret vai usar para fazer o pull da imagem
  - name: secret-dockerhub 

