apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-podmonitor
  labels:
    app: nginx-pod
spec:
  namespaceSelector:
    matchNames:
      - default # Tem que dar match com o Pod na namespace "default"
  selector:
    matchLabels:     
      app: nginx-pod # tem que dar match com o label do service
  podMetricsEndpoints: # basicamente irá indicar ao prometheus para a cada 10s fazer uma requisição para o /metrics na porta 9113, do Pod que der match com o label especificado
    - interval: 10s
      path: /metrics
      targetPort: 9113