apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
  labels:
    storage: lento
spec:
  capacity:
    storage: 1Gi
  accessModes: #Como será o modo de acesso ao PV       
    - ReadWriteOnce #Disponivel para Leitura e escrita por um unico nó
    # - ReadWriteMany #Disponivel para leitura e escrita em varios nós
    # - ReadOnlyMany #O PV Pode ser montado em varios nós, porém somente leitura
  PersistentVolumeReclaimPolicy: Retain #Reter os dados, não serão excluidos
                                 # Recycle # Os dados serão limpos e o PV será excluido quando o PVC for excluído.
                                 # Delete
  hostPath: # volume local
    path: /mnt/data # diretorio do filesystem                                    
  storageClassName: giro # vai direcionar o /mnt/data para o StorageClass "giro"
