apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: primeiro-pvc
  name: pvc
spec:
  accessModes: #Só será entregue o PV de acordo com a configuração do accessModes
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      storage: pvnfs 
  
  