apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: pvnfs
  name: pvnfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.219
    path: "/mnt/nfs"
  storageClassName: nfs
