apiVersion: kyverno.io/v1 
kind: ClusterPolicy # regra para todo o cluster
metadata:
  name: require-resources-limits
  # aqui não precisa definir namespace já que é uma policy para global
spec:
  validationFailureAction: Enforce # aqui defino se será "audit" ou "enforce", nesse caso "enforce", pois nao deve permitir de forma alguma
  rules: 
  - name: validate-limits
    match:
      resources:
        kinds: # aqui defino quais serão os objetos que farão parte da "rule", Pod, Deployment, Sts...
        - Pod 
    validate: # regra que define que será apenas validado, não será alterado (mutate) a tentantiva de criação de um pod sem limits.
      message: "Necessário definir o limite de recursos" # mensagem que será mostrada se cair na regra da validação.
      pattern: # define o padrão da regra
        spec: # spec que declara como deve ser o padrão de criação de containers, nesse caso com cpu e memória definidos
          containers: 
          - name: "*" # aplica para todos os containers
            resources:
              limits:
                cpu: "?*" # qualquer valor precisa ser definido
                memory: "?*" # qualquer valor precisa ser definido

