apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef: # referencia de qual deployment ele vai monitorar para fazer o scale up e down
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource # ira se basear no tipo de resources
    resource:
      name: cpu # tipo de resources é CPU
      target:
        type: Utilization # tipo é utilização de CPU
        averageUtilization: 50 # 50% de utilização de CPU irá se basear para escalar
