apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-hpa
  name: nginx-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hpa
  template:
    metadata:
      labels:
        app: nginx-hpa
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.02" # 2% de CPU
            memory: 32Mi # 32 Megas
