apiVersion: v1
kind: Service
metadata:
  name: nginx-nodePort
  labels:
    app: nginx
spec:
  selector: # Importante para definir qual Pod o Service vai ser atrelado
    app: nginx # todos que tiverem a label nginx
  ports:
  - port: 80 # Porta do Service
    name: http
    targetPort: 80 # Porta que o Pod está escutando para receber as requisições do Service
    nodePort: 32000
  type: NodePort