apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx  
spec: # spec de definicação do container
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template: # necessario adicionar a mesma label para o container   
    metadata:
      labels:
        app: nginx   
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # necessario definir o volumeClaim, pois setamos um volume no container
  - metadata:
      name: nginx-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi             